/*
 * Jabberwocky
 *
 * Draft version
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Connector struct {
	Name string `json:"name"`
	// connector type, either source or sink
	Type_ string `json:"type"`

	EventSources []EventSourceOrSink `json:"eventSourceInstances,omitempty"`
	EventSinks   []EventSourceOrSink `json:"eventSinkInstances,omitempty"`

	Configuration string `json:"configuration"`
}
