/*
 * Jabberwocky
 *
 * Draft version
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package server

// abstract object that can represent either an event source or event sink
type EventSourceOrSink struct {
	Name string `json:"name"`
	// the connector which produce/consume the events
	ConnectorRef string `json:"connectorRef"`

	ChannelRef string `json:"channelRef"`
	// the list of properties required by the connector
	Properties []Property `json:"properties,omitempty"`
}
