/*
 * Jabberwocky
 *
 * Draft version
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	sw "github.com/fusejw/server/internal/server"
	"github.com/gorilla/handlers"
)

func main() {
	log.Printf("Server started")

	router := sw.NewRouter()

	//log.Fatal(http.ListenAndServe(":8080", router))

	//methods := handlers.AllowedMethods([]string{"OPTIONS", "DELETE", "GET", "HEAD", "POST", "PUT"})

	log.Fatal(http.ListenAndServe(":8080",
		handlers.CORS(
			handlers.AllowedOrigins([]string{"*"}),
			handlers.AllowedMethods([]string{"OPTIONS", "DELETE", "GET", "HEAD", "POST", "PUT"}),
			handlers.AllowedHeaders([]string{"Content-Type", "*"}),
		)(router)))
}
